# Generated by Django 5.2.6 on 2025-10-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signuppage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='confirm_password',
        ),
    ]
