# Generated by Django 5.2.6 on 2025-10-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpage', '0002_uploadedfile_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='citations_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='grammar_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='improvement_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
